# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  #host: ec2-54-197-238-19.compute-1.amazonaws.com
  username: postgres
  database: ethereum
  password: postgres
  port: 5432
development:
  <<: *default